build_from:
  aarch64: ghcr.io/home-assistant/aarch64-base:3.20
  amd64: ghcr.io/home-assistant/amd64-base:3.20
  armhf: ghcr.io/home-assistant/armhf-base:3.20
  armv7: ghcr.io/home-assistant/armv7-base:3.20
  i386: ghcr.io/home-assistant/i386-base:3.20
codenotary:
  #https://github.com/codenotary/cas/issues/296
  #signer: patrick.broetto@gmail.com
  base_image: notary@home-assistant.io
args:
  EUFY_SECURITY_CLIENT_REPO: https://github.com/NachoSoto/eufy-security-client.git
  EUFY_SECURITY_CLIENT_REF: v3.8.0-t8170-stream-metadata
  EUFY_SECURITY_CLIENT_CACHE_KEY: 339e005
  EUFY_SECURITY_WS_REPO: https://github.com/NachoSoto/eufy-security-ws.git
  EUFY_SECURITY_WS_REF: v2.1.0-t8170-client
  EUFY_SECURITY_WS_CACHE_KEY: fa25a08
